### ISSUE TITLE
Release version that is compatible with latest readme

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/camunda-7-to-8-migration#108]
### What should we do?

We should create a new release, that is in sync with the readme. Especially `@EnableCamunda7Adapter` is not yet present in 0.1.1 - but described in the docs.

Not sure if current master is in shape for a 0.2.0 release maybe? @jonathanlukas ? 

### Why should we do it?

To avoid confusion for people using it

**Comment by berndruecker** [comment]
FYI: A community user just stumbled upon this

**Comment by jonathanlukas** [comment]
Thank you for the Heads up @berndruecker . 

We are planning to release 0.2.0 by the end of the week.

**Comment by berndruecker** [comment]
Great 👍 
Might also be worth to document/link how to access SNAPSHOT releases (as they are "only" on our Artifactory (https://artifacts.camunda.com/ui/packages/gav:%2F%2Forg.camunda.community.migration:camunda-7-adapter?name=camunda-7-adapter&type=packages and not on Maven Central)
