### ISSUE TITLE
Couple BPMN Message elements to their events

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#131]
### Is your feature request related to a problem? Please describe.

When you have a process with a lot of message events, you get hints for each message element. Like

```
message Message_13w74np PERMISSION_TO_OPERATE

    TASK: Please define a correlation key.
```

They are hard to find in the diagram, as they are indirectly bound to intermediate or boundary events.

### Describe the solution you'd like

Couple the output of the message to the events that are referencing them.

Then the event can be highlighted in the diagram.

### Describe alternatives you've considered

nothing

### Additional context

nothing

**Comment by jonathanlukas** [comment]
The message belongs to the event element, so it should stay there in the result.
What could be done is to create references in the result towards the event element:

Current element result:
```
{
    "messages": [],
    "elementId": "sendMessageEndEvent",
    "elementName": "Result sent to requester",
    "elementType": "endEvent"
}
```

Could be:

```
{
    "messages": [],
    "elementId": "sendMessageEndEvent",
    "elementName": "Result sent to requester",
    "elementType": "endEvent",
    "references": "Message_12345"
}
```

This would make it easy for an implementation against the API to find related messages as well.

wdyt @ingorichtsmeier ?

**Comment by ingorichtsmeier** [comment]
This could be a first step to make it easier.

But the better solution is to add the output for the message element to the boundary event directly. 

The person using the modeler didn't see the extra BPMN Element for the message in the canvas or the property panel.

**Comment by ingorichtsmeier** [comment]
We can play with this diagram to find the best solution: 
[message-example - Kopie.bpmn.txt](https://github.com/camunda-community-hub/camunda-7-to-8-migration/files/10141218/message-example.-.Kopie.bpmn.txt)

**Comment by jonathanlukas** [comment]
Making the output readable is not part of the JSON response rather than the tool that presents the results.

What I found out during working with the linter rules is that it would probably make sense to create bidirectional relations:
```
{
    "messages": [],
    "elementId": "sendMessageEndEvent",
    "elementName": "Result sent to requester",
    "elementType": "endEvent",
    "references": ["Message_12345"]
}
```
and
```
{
    "messages": [],
    "elementId": "Message_12345",
    "elementName": "sendSomethingMessage",
    "elementType": "message",
    "referencedBy": ["sendMessageEndEvent"]
}
```
The references can be used to find related events quite fast-forward.

The referencedBy helps the linter to find the element ids the linter rules should be presented on.

The same would apply to any bpmn-js plugin and the structured presentation of results.

**Comment by jonathanlukas** [comment]
With a more intelligent linter rule, this works like a charm, even without the references in the JSON 
![image](https://user-images.githubusercontent.com/81753891/205306914-7652f888-6d34-4f77-b77c-cc854fdc79d3.png)

Is this the desired result @ingorichtsmeier ?

**Comment by ingorichtsmeier** [comment]
yes.

I think that the severity should be WARNING, as an active change is required and the action is more than double check.

**Comment by jonathanlukas** [comment]
A `WARNING` tells you that something is not possible with Camunda 8.

A task is a general call to action. This might be a double-check or something that needs to be defined by the modeling person.

**Comment by ingorichtsmeier** [comment]
Yeah, I'm unsure here. 

Right now we have only tasks to double-check, and the model can be deployed without following them. 

Without a correlation, Zeebe rejects the deployment. From the modeler linting you will get an ERROR.

And the correlation variable is not obvious when you compare message correlation in Camunda 7 and 8. 

These are arguments to set it to WARNING.

Maybe we should change our informal definition of WARNING: You have to do something to get the process diagram running on Camunda 8. This will include everything that is not possible in Camunda 8. And could be supported with links to more documentation.

**Comment by jonathanlukas** [comment]
We should discuss this in a separate ticket. I will create one and mention this discussion.

I would like to share what my latest progress is capable to do with the check result:

![image](https://user-images.githubusercontent.com/81753891/205348071-0b1f91fa-87ef-43e2-9e60-d874959461a7.png)

Also, all receive events are marked with a `TASK`.

I will create a PR to close this ticket.
