### ISSUE TITLE
All messages in the CSV download should be a single line...

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#149]
### Is your feature request related to a problem? Please describe.

... even if it's long.

I found the hint:
```
Element 'inputParameter' was transformed. Parameter 'thirdPartyTrackingItems': Please review transformed expression: '${S('[{
  "trackingItemType": "123",
  "category": "234",
  "subcategory": "345",
  "reasons": "456",
  "displayName":"567",
  "targetParty": "678",
  "externalFacingText": "",
  "clientFacing": false
}]')}' -> '${S('[{
  "trackingItemType": "123",
  "category": "234",
  "subcategory": "345",
  "reasons": "456",
  "displayName":"567",
  "targetParty": "678",
  "externalFacingText": "",
  "clientFacing": false
}]')}'.
```

### Describe the solution you'd like

Even if it's a long output, all line breaks should be replaced with a single space.

### Describe alternatives you've considered

nothing

### Additional context

I could not find the message from the check result in the Excel file, as there were many messages and the relevant content was hidden in the cell.

I cannot share the original diagram, it's confidential.

**Comment by jonathanlukas** [comment]
After our discussion yesterday, we will not do this (for now).
