### ISSUE TITLE
Migrated BPMN does not deploy in Zeebe

### ISSUE THREAD

**Issue by stephanpelikan** [camunda-community-hub/camunda-7-to-8-migration#19]
After applying migration to a C7 BPMN I had to close the file, restart the Modeler and open the file again to get C8 controls in property panel. However, I did all the manual adaption and tried to deploy the model to the Zeebe-cluster for which I faced this error:

1. `INVALID_ARGUMENT: Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'Test.bpmn': Unable to process unknown element with name inputOutput` caused by this BPMN sections:
```xml
      <bpmn:extensionElements>
        <camunda:inputOutput>
          <camunda:inputParameter name="TestLoop">${loopCounter}</camunda:inputParameter>
        </camunda:inputOutput>
```
This can be solved by the migration plugin by simply removing the tag or by translating this to `zeebe:ioMapping`.

2. Additionally, I faced a lot of errors caused by elements of a non-executable pool like
   `Element: ConditionalEventDefinition_0lvmueg ERROR: Event definition of this type is not supported` *Why does Zeebe not simply ignore those elements?* Removing them changes the meaning of the BPMN diagram or reduces its readabilty. Where is the best place to add this as an issue or if it already exists to vote for it?

3. And another one as part of migrating the BPMN to Camunda 8: An event-start element gives an error in the Modeler for a missing correlation key but start-events do not have correlation keys:
![zeebe_start_event](https://user-images.githubusercontent.com/5190548/173783183-8dcfed2a-7faa-43a9-a0e6-fc4e85ab482f.png)

**Comment by stephanpelikan** [comment]
Hi @berndruecker,

Thank you for your quick response, especially for creating the related issues!

Regarding message-start-event:

> Message start events must have a correlation key, only blanko events do not

The Modeler does not provide that input field for the correlation key in property panel as it does for the common receive-tasks!?
Of course, if you have several message correlations in the diagram for the same message then you need a correlation key to distinguish them from each other - even message start events. But in 99% of all message start events there is no correlation key in a semantical manner.

I also tested this and I am able to start the process by message correlation. The Zeebe-client requires to defined a correlation key but the BPMN without that key can be deploy into Zeebe and therefore the actual correlation key seems to be ignored.

From a C7 user's perspective everything is fine, there is only this warning in the Modeler which causes confusion.

**Comment by jonathanlukas** [comment]
Hello @stephanpelikan , could you please try the new [diagram-converter](https://diagram-converter.consulting-sandbox.camunda.cloud)? It is based on the backend-diagram-converter/webapp and hosted by the camunda consulting team.

This bug disappeared for me now when using it in combination with modeler 5.4.x.

Can you confirm this?
