### ISSUE TITLE
Display the version in the web page.

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#193]
### Is your feature request related to a problem? Please describe.

Right now, you cannot see which version of the diagram converter is used when you open the web page.

### Describe the solution you'd like

We should display the version on the web page.

### Describe alternatives you've considered

nothing

### Additional context

Do we already insert the converter version into the converted diagrams?

**Comment by ingorichtsmeier** [comment]
@jonathanlukas, I hope you know this out of your head:

 >Do we already insert the converter version into the converted diagrams?

**Comment by jonathanlukas** [comment]
No, we don't. This is something we could start doing.
