### ISSUE TITLE
Input mapping with empty String causes a FEEL error

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#198]
### Describe the bug

The converter maps an empty input mapping (without a value) to a FEEL syntax error.

As a modeler you use empty input values to initialize local variables with empty Strings.

The mapped result is currently:

```
<zeebe:input source="=" target="rueckforderungsart"/>
```

### Steps to reproduce

Convert a process with an input mapping like

```
<camunda:inputParameter name="rueckforderungsart" />
```

### Expected Behaviour

The result is a valid FEEL expression.

Usually the  user wants to initalize a value to 

### Library version

0.4.3

### Camunda version

egal

### Camunda Distribution

other

**Comment by jonathanlukas** [comment]
>Usually the user wants to initalize a value to

To what? I would initialize it to `null` to not determine the data type upfront.

**Comment by ingorichtsmeier** [comment]
I think it depends on the magic of the type conversion.

We should get the details what happens in Camunda 7 with this input mapping: `<camunda:inputParameter name="rueckforderungsart" />` and find a valid init value. I got distracted when I typed it.

**Comment by jonathanlukas** [comment]
A variable is type-agnostic, so initializing it to null will just create an empty variable scope with no data which should be exactly what was intended with an empty value in Camunda 7.
