### ISSUE TITLE
Migrate `<camunda:inputOutput>`

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/camunda-7-to-8-migration#20]
Having an IO mapping leads to `INVALID_ARGUMENT: Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'Test.bpmn': Unable to process unknown element with name inputOutput` caused by this BPMN sections:
```xml
      <bpmn:extensionElements>
        <camunda:inputOutput>
          <camunda:inputParameter name="TestLoop">${loopCounter}</camunda:inputParameter>
        </camunda:inputOutput>
```
This can be solved by the migration plugin by translating this to `zeebe:ioMapping`. (raised in https://github.com/camunda-community-hub/camunda-7-to-8-migration/issues/19)

**Comment by jonathanlukas** [comment]
Closed with #28 for backend conversion.
