### ISSUE TITLE
Provide a migration check for models on the web

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#21]
We should refactor the modeler plugin to provide a basic bpmn-js plugin that can be used in a simple web page in any browser.

This could serve for a simple precheck if a Camunda 7 model can be converted without the need to install the modeler plugin on customers desktop modeler.

Perhaps the errors from the linter in the desktop modeler has to be handled seperately to show unsupported bpmn elements (e.g. signal events) and missing configuration (e.g. correlation key for message catch events).

**Comment by ingorichtsmeier** [comment]
Initial library to started here: https://github.com/camunda-community-hub/camunda-7-to-8-migration/tree/model-inspection-browser/bpmn-js-7-to-8-migration-extension (branch model-inspection-browser)

It uses karma tests for quick feedback on new process models.

**Comment by ingorichtsmeier** [comment]
The BPMN js developers pointed me to use bpmn-moddle as the unterlying library. Then it would be possible to wrap the library in a command line tool as well.

**Comment by jonathanlukas** [comment]
As @ingorichtsmeier and me discussed today, a backend-based webapp could serve here as well.
In this case, development of the tool would be done with #28 .
