### ISSUE TITLE
Add hints about listeners in bpmn models

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#22]
If a process model for Camunda 7 uses task or execution listeners, the converter should highlight them.

They require separate inspection and actions. 

Showing the implementation details like classname, delegate expression or listener id (for task listeners) in the overlay may already give a hint about the purpose of the listener.

**Comment by jonathanlukas** [comment]
Would this one be closed with #28 ?
