### ISSUE TITLE
Add a camunda-engine artifact with @deprecated on non-supported `delegateExecution` methods

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#26]
Create a new artifact with maven overlays, that adds `@deprecated` annotations to all methods that are not directly mappable to Camunda 8 constructs.

This library could be added in projects to assess the usage of code that violates the Clean Delegate implementation.

The IDE will show all deprecated usages and the project team could estimate the effort to spend on migration for this code.

**Comment by jonathanlukas** [comment]
I am not sure how this exactly works, but it sounds really nice.

**Comment by jonathanlukas** [comment]
@ingorichtsmeier This could also work by using the code check #279 
wdyt?

**Comment by ingorichtsmeier** [comment]
I agree. After trying the code checker, I can hopefully close this issue as done.
