### ISSUE TITLE
Idea to support execution listeners

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#27]
* Add additional headers to the Camunda 8 service task with class names for the listener implementation
* Invoke the start listeners before the delegate implementation
* Invoke the end listeners after the delegate implementation

Assumption: listeners have to be "clean" as well, e.g. they should not invoke `execution.getProcessEngineServices()`.

The transaction behavior is handled in the task worker as all methods are called in a given sequence and any exception is catched in the adapter.

**Comment by jonathanlukas** [comment]
Scope: Only the migration tool will support this.

**Comment by jonathanlukas** [comment]
@jangalinski tagging you here to match your PR from the hackday with the issue

**Comment by jangalinski** [comment]
see #280
