### ISSUE TITLE
Camunda-7-Adapter cannot handle Object process variables

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#299]
### Describe the bug

Running a process that uses object variables in Camunda 7 could not run in Camunda 8, as you get errors converting the JSON variables into the typed objects that the migrated project provides.

### Steps to reproduce

To be refined.

Try to convert a process where the delegate uses a DTO.

### Expected Behaviour

I don't know if this is possible at all. If not, write at least a warning in the documentation about this limitation.

A workaround is to write a dedicated worker and reuse your DTO with `@VariableAsType`.

### Library version

latest

### Camunda version

latest

### Camunda Distribution

other

**Comment by fml2** [comment]
> A workaround is to write a dedicated worker and reuse your DTO with @VariableAsType

IMO it should be `@Variable`, not `@VariableAsType`.

**Comment by jonathanlukas** [comment]
Idea: Introduce mapping rules:
processDefinition -> variableName -> type
