### ISSUE TITLE
Migration does not add `zeebe` namespace to `<definitions` if no Zeebe attribute is set in the whole model

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/camunda-7-to-8-migration#3]
Happens if you 

* create a new model in Cawemo
* Export it (it does not contain Camunda Platform attributes)
* Migrate (it does not write any Zeebe attributes)

The resulting XML does not contain the Zeebe namespace and the modeler opens it as Camunda Platform model

**Comment by jonathanlukas** [comment]
Closed for backend migration with #28
