### ISSUE TITLE
Handle conditions in sequence flows implemented as scripts

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#319]
### What should we do?

If a condition in a sequence flow is modeled as script, we should adjust the conversion message.

Right now it says:
```
Condition expression: Transformed expression: 'var codexResponse = new String(execution.getVariable("codexResponse"))
```

Scripts should only be transformed, if the result is a valid FEEL expression.

My suggestion: WARNING: Condition implemented in {{scriptFormat}} are not supported in Zeebe. Try to create a FEEL function from the script. 

### Why should we do it?

I found a process model with some conditions like this:

```
var codexResponse = new String(execution.getVariable("codexResponse"))
if(codexResponse.indexOf("\"pid\":\"-1") > -1) {
true
} else {
false
}
```
Type: Script, Format: JavaScript, Script type: Inline script

A FEEL function seems to be possible here.

**Comment by jonathanlukas** [comment]
Using a script instead of an expression will create a conditionExpression like this:
```xml
<bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="javascript">whatever</bpmn:conditionExpression>
```
So, we should have a look at the attribute `language`.
