### ISSUE TITLE
Present converted model in BPMN viewer after conversion on webapp

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/camunda-7-to-8-migration#56]
### Is your feature request related to a problem? Please describe.

When converting a model, currently the presentation is text-only. By enhancing this with a model viewer, the visual would be better.

### Describe the solution you'd like

Above the results of the conversion, there should be a space for the diagram to be rendered.

### Describe alternatives you've considered

After conversion, you can inspect the downloaded diagram in the Camunda Modeler. However, not every person has one at hand.

### Additional context

-

**Comment by ingorichtsmeier** [comment]
Topics to solve:
* Size of the viewer? It's 250px now
* Add overlays from [property info plugin](https://github.com/mesoneer-ag/camunda-modeler-property-info-plugin)
* Add overlays from [tooltip plugin](https://github.com/viadee/camunda-modeler-tooltip-plugin)
* Add overlays for conversion hints. Mark converted elements, show details when mouse hovers the element.

**Comment by ingorichtsmeier** [comment]
Done with #89
