### ISSUE TITLE
Reframe warnings of diagram check to be constructive

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/camunda-7-to-8-migration#57]
### What should we do?

Rephrase warnings to be constructive so that a person who checks a diagram does not just see what cannot be done but how a workaround could look like

### Why should we do it?

The conversion tool would be much more helpful

**Comment by jonathanlukas** [comment]
Also in scope is to define a link for each message that points to a helpful information source

**Comment by ingorichtsmeier** [comment]
With refactoring, the base is laid to change each message individually.

Let's close this and open more specific issues for single messages.
