### ISSUE TITLE
Improve the JuelToFeelConverter in Backend

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/camunda-7-to-8-migration#60]
### Is your feature request related to a problem? Please describe.

Currently, the Juel to Feel converter is very simple and does not cover all relevant cases.

### Describe the solution you'd like

Port the existing js converter to Java

### Describe alternatives you've considered

Use the existing JS converter with the embedded JS engine

### Additional context

no

**Comment by ingorichtsmeier** [comment]
Closed by merging #66
