### ISSUE TITLE
Enhance code-migration-detector to allow code analysis.

### ISSUE THREAD

**Issue by ManuelDittmar** [camunda-community-hub/camunda-7-to-8-migration#852]
### Is your feature request related to a problem? Please describe.

Migration effort can be seen based on the diagram converter, however currently there is no tooling available to analyze the code base. 

### User Story
As a system architect,
I want to ensure that no new implementations are added using Camunda 7 specific APIs and patterns,
so that we avoid complicating the upcoming migration to Camunda 8.
### Acceptance criteria

- Given that that a developer is adding or modifying a process solution,
- when the changes are submitted,
- then the CI/CD pipeline should automatically check for and reject any use of deprecated Camunda 7 APIs

### Tasks
- Develop ArchUnit rules to detect deprecated Camunda 7 APIs
- Allow ignoring old violations

### User Story
As a system architect,
I want to have the ability to trigger an analysis that generates a detailed report of Camunda 7 architectural violations
so that I can proactively assess and plan the migration to Camunda 8
### Acceptance criteria
- Given that I trigger the analysis,
- when  the analysis runs on the current codebase,
- then the tool should evaluate the current code base for Camunda 7-specific architectural violations, generate a detailed report that includes each violation, explains the implications for migration to Camunda 8, and provides suggestions that conform to Camunda 8 best practices, potentially linking to documentation or examples for further guidance.
## Tasks
- Enhance ArchUnit reporting to include detailed violation analysis and migration guidance
- Document how to generate a report on-demand.

### Missing Tests
- Engine Plugin

### Describe alternatives you've considered

- For now I would like to build the solution on top of the existing ArchUnit Implementation: https://github.com/camunda-community-hub/camunda-7-to-8-migration/tree/main/code-migration-detector 

### Additional context

Implementation will be discussed with @jonathanlukas

**Comment by ingorichtsmeier** [comment]
I've improved the README with a working `MigrationPreparationTest`.
