### ISSUE TITLE
Convert RetryTimeCycle to Retries

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-7-to-8-migration#87]
### Describe the bug

I have a service task with asyncBefore and RetryTimeCycle `R4/PT10S`. 

Hint after conversion says: 

```
TASK: Element 'failedJobRetryTimeCycle' was transformed, please review. Hint: Retry time cycle works different in Zeebe. Please review your implementation
```

But the retries on the task definition of the converted process is still empty. 

### Steps to reproduce

Convert a process model with a service task with async before and retryTimeCycle set.

### Expected Behaviour

The retries on the converted process is set to `4`.

The hint is adjusted.

Or change the hint to ' ... is removed' .

### Library version

0.1.2-SNAPSHOT

### Camunda version

7

### Camunda Distribution

other

**Comment by ingorichtsmeier** [comment]
After look into the code, I found that the conversion is loosely coupled. 

And the amount of abstract visitors is overwhelming.

Some visitors call `org.camunda.community.converter.visitor.AbstractSupportedAttributeVisitor.visitSupportedAttribute(DomElementVisitorContext, String)` to return a hint.

The conversion happens as a side effect in the method by

```
  protected String visitSupportedAttribute(DomElementVisitorContext context, String attribute) {
    context.addConversion(
        ServiceTaskConvertible.class,
        serviceTaskConversion ->
            serviceTaskConversion.addZeebeTaskHeader(attributeLocalName(), attribute));
    context.addConversion(
        ServiceTaskConvertible.class,
        serviceTaskConversion ->
            serviceTaskConversion.getZeebeTaskDefinition().setType(CAMUNDA_7_ADAPTER));
    return "Delegate call to '"
        + attribute
        + "' was transformed to job type '"
        + CAMUNDA_7_ADAPTER
        + "'. Please review your implementation";
  }
```

But only some visitors implement methods that return a String as a hint to the inspected DomElement.

Which one do something, which don't? It sound like a valid request to simplify the structure.

```
```

**Comment by ingorichtsmeier** [comment]
Current Visitor structure:

![grafik](https://user-images.githubusercontent.com/7870843/201371609-3670195b-7f72-4628-8427-fb5d91d8ce7f.png)

more subclasses on `AbstractAttributeVisitor`:

![grafik](https://user-images.githubusercontent.com/7870843/201371868-ae8635a2-fe5d-4de0-be13-676b72aae5c5.png)

more Subclasses on `AbstractElementVisitor`:

![grafik](https://user-images.githubusercontent.com/7870843/201372083-404c5605-3751-4c14-b6a3-ca81ae35b808.png)

**Comment by jonathanlukas** [comment]
Was fixed in extraction of messages to properties file. The current message states:

```
TASK: Element 'failedJobRetryTimeCycle' cannot be transformed. The timecycle 'R5/PT10S' has to be transformed to Retries.
```

**Comment by ingorichtsmeier** [comment]
The value `5` is the expected value for retries.

Only the period is dropped and should be handled by the worker.
